//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSVS.FAS.EDR.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emotion_Training_Data
    {
        public int id { get; set; }
        public string Emotion_Name { get; set; }
        public double Emotion_Value { get; set; }
    }
}
