//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSVS.FAS.EDR.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emotion_distances
    {
        public int id { get; set; }
        public double LEB_CPLE { get; set; }
        public double REB_CPRE { get; set; }
        public double OPEN_LE { get; set; }
        public double OPEN_RE { get; set; }
        public double OPEN_MO { get; set; }
        public double EXP_MO { get; set; }
        public double CPLE_CPMO { get; set; }
        public double CPRE_CPMO { get; set; }
        public double LPLE_CPMO { get; set; }
        public double RPRE_CPMO { get; set; }
        public string Label { get; set; }
    }
}
