//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSVS.FAS.EDR.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emotiondbEntities1 : DbContext
    {
        public emotiondbEntities1()
            : base("name=emotiondbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emotion_Training_Data> Emotion_Training_Data { get; set; }
        public virtual DbSet<Emotion_Training_distances> Emotion_Training_distances { get; set; }
        public virtual DbSet<Emotion_training_distances_wrinkle_free> Emotion_training_distances_wrinkle_free { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Emotion_distances> Emotion_distances { get; set; }
    }
}
