//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSVS.FAS.EDR.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emotion_training_distances_wrinkle_free
    {
        public int id { get; set; }
        public double LEB1_CPLE1 { get; set; }
        public double LEB2_CPLE2 { get; set; }
        public double REB1_CPRE1 { get; set; }
        public double REB2_CPRE2 { get; set; }
        public double OPEN_LE1 { get; set; }
        public double OPEN_LE2 { get; set; }
        public double OPEN_RE1 { get; set; }
        public double OPEN_RE2 { get; set; }
        public double EXP_MO { get; set; }
        public double OPEN_MO1 { get; set; }
        public double OPEN_MO2 { get; set; }
        public double OPEN_MO3 { get; set; }
        public string Label { get; set; }
    }
}
